/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_jaffe2718_whisperjni_WhisperJNI */

#ifndef _Included_io_github_jaffe2718_whisperjni_WhisperJNI
#define _Included_io_github_jaffe2718_whisperjni_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    init
 * Signature: (Ljava/lang/String;Lio/github/jaffe2718/whisperjni/WhisperContextParams;)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_init
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    initFromInputStream
 * Signature: (Ljava/io/InputStream;Lio/github/jaffe2718/whisperjni/WhisperContextParams;)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_initFromInputStream
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    initNoState
 * Signature: (Ljava/lang/String;Lio/github/jaffe2718/whisperjni/WhisperContextParams;)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_initNoState
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    initState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_initState
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    loadGrammar
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_loadGrammar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    initOpenVINOEncoder
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_initOpenVINOEncoder
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    isMultilingual
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_isMultilingual
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    full
 * Signature: (ILio/github/jaffe2718/whisperjni/WhisperFullParams;[FI)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_full
  (JNIEnv *, jobject, jint, jobject, jfloatArray, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullWithState
 * Signature: (IILio/github/jaffe2718/whisperjni/WhisperFullParams;[FI)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullWithState
  (JNIEnv *, jobject, jint, jint, jobject, jfloatArray, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullNTokens
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullNTokens
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullNTokensFromState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullNTokensFromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    getTokenData
 * Signature: (III)Lio/github/jaffe2718/whisperjni/TokenData;
 */
JNIEXPORT jobject JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_getTokenData
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    getTokenDataFromState
 * Signature: (IIII)Lio/github/jaffe2718/whisperjni/TokenData;
 */
JNIEXPORT jobject JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_getTokenDataFromState
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    vadState
 * Signature: (IILio/github/jaffe2718/whisperjni/WhisperFullParams;Lio/github/jaffe2718/whisperjni/WhisperVADContextParams;[FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_vadState
  (JNIEnv *, jobject, jint, jint, jobject, jobject, jfloatArray, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullNSegments
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullNSegments
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullNSegmentsFromState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullNSegmentsFromState
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp0
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullGetSegmentTimestamp0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp1
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullGetSegmentTimestamp1
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullGetSegmentText
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullGetSegmentText
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp0FromState
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullGetSegmentTimestamp0FromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp1FromState
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullGetSegmentTimestamp1FromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTextFromState
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_fullGetSegmentTextFromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    freeContext
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_freeContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    freeState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_freeState
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    freeGrammar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_freeGrammar
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    printSystemInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_printSystemInfo
  (JNIEnv *, jobject);

/*
 * Class:     io_github_jaffe2718_whisperjni_WhisperJNI
 * Method:    setLogger
 * Signature: (Lorg/slf4j/Logger;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaffe2718_whisperjni_WhisperJNI_setLogger
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
