/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_clip_whisperjni_WhisperJNI */

#ifndef _Included_jp_clip_whisperjni_WhisperJNI
#define _Included_jp_clip_whisperjni_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    init
 * Signature: (Ljava/lang/String;Ljp/clip/whisperjni/WhisperContextParams;)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_init
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    initFromInputStream
 * Signature: (Ljava/io/InputStream;Ljp/clip/whisperjni/WhisperContextParams;Z)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_initFromInputStream
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    initNoState
 * Signature: (Ljava/lang/String;Ljp/clip/whisperjni/WhisperContextParams;)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_initNoState
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    initState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_initState
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    loadGrammar
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_loadGrammar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    initOpenVINOEncoder
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_clip_whisperjni_WhisperJNI_initOpenVINOEncoder
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    isMultilingual
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_clip_whisperjni_WhisperJNI_isMultilingual
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    full
 * Signature: (ILjp/clip/whisperjni/WhisperTranscriptionParams;[FI)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_full
  (JNIEnv *, jobject, jint, jobject, jfloatArray, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullWithState
 * Signature: (IILjp/clip/whisperjni/WhisperTranscriptionParams;[FI)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullWithState
  (JNIEnv *, jobject, jint, jint, jobject, jfloatArray, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullNSegments
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullNSegments
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullNSegmentsFromState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullNSegmentsFromState
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp0
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullGetSegmentTimestamp0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp1
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullGetSegmentTimestamp1
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullGetSegmentText
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullGetSegmentText
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp0FromState
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullGetSegmentTimestamp0FromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp1FromState
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullGetSegmentTimestamp1FromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTextFromState
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_clip_whisperjni_WhisperJNI_fullGetSegmentTextFromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    getSegmentTokens
 * Signature: (II)[Ljp/clip/whisperjni/WhisperToken;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_clip_whisperjni_WhisperJNI_getSegmentTokens
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    getSegmentTokensFromState
 * Signature: (III)[Ljp/clip/whisperjni/WhisperToken;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_clip_whisperjni_WhisperJNI_getSegmentTokensFromState
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    printSystemInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_clip_whisperjni_WhisperJNI_printSystemInfo
  (JNIEnv *, jobject);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    freeContext
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_clip_whisperjni_WhisperJNI_freeContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    freeState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_clip_whisperjni_WhisperJNI_freeState
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    freeGrammar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_clip_whisperjni_WhisperJNI_freeGrammar
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_clip_whisperjni_WhisperJNI
 * Method:    setLogger
 * Signature: (Lorg/slf4j/Logger;)V
 */
JNIEXPORT void JNICALL Java_jp_clip_whisperjni_WhisperJNI_setLogger
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
